/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogomemoria.gui;

/**
 *
 * @author Aluno
 */
public class JogoMemoriaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form JogoMemoriaJPanel
     */
    public JogoMemoriaJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jq176 = new javax.swing.JLabel();
        jq181 = new javax.swing.JLabel();
        jq180 = new javax.swing.JLabel();
        jq170 = new javax.swing.JLabel();
        jq168 = new javax.swing.JLabel();
        jq169 = new javax.swing.JLabel();
        jq171 = new javax.swing.JLabel();
        jq147 = new javax.swing.JLabel();
        jq152 = new javax.swing.JLabel();
        jq153 = new javax.swing.JLabel();
        jq131 = new javax.swing.JLabel();
        jq157 = new javax.swing.JLabel();
        jq148 = new javax.swing.JLabel();
        jq166 = new javax.swing.JLabel();
        jq164 = new javax.swing.JLabel();
        jq165 = new javax.swing.JLabel();
        jq173 = new javax.swing.JLabel();
        jq163 = new javax.swing.JLabel();
        jq162 = new javax.swing.JLabel();
        jq177 = new javax.swing.JLabel();
        jq179 = new javax.swing.JLabel();
        jq146 = new javax.swing.JLabel();
        jq151 = new javax.swing.JLabel();
        jq158 = new javax.swing.JLabel();
        jq159 = new javax.swing.JLabel();
        jq136 = new javax.swing.JLabel();
        jq161 = new javax.swing.JLabel();
        jq135 = new javax.swing.JLabel();
        jq160 = new javax.swing.JLabel();
        jq178 = new javax.swing.JLabel();
        jq149 = new javax.swing.JLabel();
        jq154 = new javax.swing.JLabel();
        jq143 = new javax.swing.JLabel();
        jq140 = new javax.swing.JLabel();
        jq155 = new javax.swing.JLabel();
        jq134 = new javax.swing.JLabel();
        jq137 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jq150 = new javax.swing.JLabel();
        jq156 = new javax.swing.JLabel();
        jq175 = new javax.swing.JLabel();
        jq174 = new javax.swing.JLabel();
        jq172 = new javax.swing.JLabel();
        jq145 = new javax.swing.JLabel();
        jq144 = new javax.swing.JLabel();
        jq142 = new javax.swing.JLabel();
        jq133 = new javax.swing.JLabel();
        jq138 = new javax.swing.JLabel();
        jq141 = new javax.swing.JLabel();
        jq139 = new javax.swing.JLabel();
        jq132 = new javax.swing.JLabel();
        jq130 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        titulo8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));

        jq176.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/26.png"))); // NOI18N

        jq181.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/26.png"))); // NOI18N

        jq180.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/26.png"))); // NOI18N

        jq170.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/27.jpg"))); // NOI18N

        jq168.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/25_1.png"))); // NOI18N

        jq169.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/25_1.png"))); // NOI18N

        jq171.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/25_1.png"))); // NOI18N

        jq147.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/11.jpg"))); // NOI18N

        jq152.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/11.jpg"))); // NOI18N

        jq153.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7.jpg"))); // NOI18N

        jq131.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/9.jpg"))); // NOI18N

        jq157.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/17.jpg"))); // NOI18N

        jq148.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/17.jpg"))); // NOI18N

        jq166.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/12.jpg"))); // NOI18N

        jq164.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/17.jpg"))); // NOI18N

        jq165.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7.jpg"))); // NOI18N

        jq173.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/9.jpg"))); // NOI18N

        jq163.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/24.jpg"))); // NOI18N

        jq162.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/19.jpg"))); // NOI18N

        jq177.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/20.jpg"))); // NOI18N

        jq179.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/23.jpg"))); // NOI18N

        jq146.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/23.jpg"))); // NOI18N

        jq151.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/21.jpg"))); // NOI18N

        jq158.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/21.jpg"))); // NOI18N

        jq159.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/21.jpg"))); // NOI18N

        jq136.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/23.jpg"))); // NOI18N

        jq161.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/19.jpg"))); // NOI18N

        jq135.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/27.jpg"))); // NOI18N

        jq160.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/24.jpg"))); // NOI18N

        jq178.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/27.jpg"))); // NOI18N

        jq149.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/20.jpg"))); // NOI18N

        jq154.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/20.jpg"))); // NOI18N

        jq143.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/12.jpg"))); // NOI18N

        jq140.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/15.jpg"))); // NOI18N

        jq155.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/12.jpg"))); // NOI18N

        jq134.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/15.jpg"))); // NOI18N

        jq137.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/15.jpg"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/24.jpg"))); // NOI18N

        jq150.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/11.jpg"))); // NOI18N

        jq156.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7.jpg"))); // NOI18N

        jq175.setBackground(new java.awt.Color(153, 255, 255));
        jq175.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/9.jpg"))); // NOI18N

        jq174.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/6.jpg"))); // NOI18N

        jq172.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/6.jpg"))); // NOI18N

        jq145.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/6.jpg"))); // NOI18N

        jq144.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/5.jpg"))); // NOI18N

        jq142.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/5.jpg"))); // NOI18N

        jq133.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/5.jpg"))); // NOI18N

        jq138.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.jpg"))); // NOI18N

        jq141.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.jpg"))); // NOI18N

        jq139.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/2.jpg"))); // NOI18N

        jq132.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1.jpg"))); // NOI18N

        jq130.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1.jpg"))); // NOI18N

        l9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1.jpg"))); // NOI18N

        titulo8.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        titulo8.setText("Jogo da Memória");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/19.jpg"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Last Time");

        jSlider1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Volume");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jq151)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jq158))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jq168)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jq169)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jq171)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jq176)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jq181)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jq180)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jq170)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jq135))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jq159)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jq136))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jq157)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(2, 2, 2)
                        .addComponent(jq179)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(426, 426, 426)
                                .addComponent(jLabel1)
                                .addGap(146, 146, 146)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jq146)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jq163)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jq160)))))
                .addGap(262, 262, 262))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jq150)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jq147)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jq152)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jq166)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jq155))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jq164)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jq148))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jq145)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jq172)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jq174)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jq165)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jq153)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jq156)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jq173))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jq161)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jq162)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jq154)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jq143)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jq134)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jq137)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jq140))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jq177)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jq178)
                                            .addComponent(jq149)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(jq175)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jq131))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(titulo8)
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(l9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jq130)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jq132)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jq139)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jq141)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jq138)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jq133)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jq142)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jq144))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titulo8)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jq144)
                    .addComponent(l9)
                    .addComponent(jq130)
                    .addComponent(jq132)
                    .addComponent(jq139)
                    .addComponent(jq141)
                    .addComponent(jq138)
                    .addComponent(jq142)
                    .addComponent(jq133))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jq145)
                            .addComponent(jq172)
                            .addComponent(jq174)
                            .addComponent(jq165)
                            .addComponent(jq173)
                            .addComponent(jq153)
                            .addComponent(jq156))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jq150)
                                    .addComponent(jq147)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jq155)
                                    .addComponent(jq134)
                                    .addComponent(jq166)
                                    .addComponent(jq152)
                                    .addComponent(jq143)
                                    .addComponent(jq137)
                                    .addComponent(jq140)))))
                    .addComponent(jq175)
                    .addComponent(jq131))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jq178)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jq164)
                                        .addComponent(jq157))
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jq148, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jq161, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jq162, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jq154, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jq177, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jq149, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jq151)
                                            .addComponent(jq158)
                                            .addComponent(jq159)
                                            .addComponent(jq136)
                                            .addComponent(jq179)
                                            .addComponent(jq146)
                                            .addComponent(jq163)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jq160)
                                            .addComponent(jLabel10)))))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jq168)
                            .addComponent(jq169)
                            .addComponent(jq171)
                            .addComponent(jq176)
                            .addComponent(jq181)
                            .addComponent(jq180)
                            .addComponent(jq170)
                            .addComponent(jq135))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel jq130;
    private javax.swing.JLabel jq131;
    private javax.swing.JLabel jq132;
    private javax.swing.JLabel jq133;
    private javax.swing.JLabel jq134;
    private javax.swing.JLabel jq135;
    private javax.swing.JLabel jq136;
    private javax.swing.JLabel jq137;
    private javax.swing.JLabel jq138;
    private javax.swing.JLabel jq139;
    private javax.swing.JLabel jq140;
    private javax.swing.JLabel jq141;
    private javax.swing.JLabel jq142;
    private javax.swing.JLabel jq143;
    private javax.swing.JLabel jq144;
    private javax.swing.JLabel jq145;
    private javax.swing.JLabel jq146;
    private javax.swing.JLabel jq147;
    private javax.swing.JLabel jq148;
    private javax.swing.JLabel jq149;
    private javax.swing.JLabel jq150;
    private javax.swing.JLabel jq151;
    private javax.swing.JLabel jq152;
    private javax.swing.JLabel jq153;
    private javax.swing.JLabel jq154;
    private javax.swing.JLabel jq155;
    private javax.swing.JLabel jq156;
    private javax.swing.JLabel jq157;
    private javax.swing.JLabel jq158;
    private javax.swing.JLabel jq159;
    private javax.swing.JLabel jq160;
    private javax.swing.JLabel jq161;
    private javax.swing.JLabel jq162;
    private javax.swing.JLabel jq163;
    private javax.swing.JLabel jq164;
    private javax.swing.JLabel jq165;
    private javax.swing.JLabel jq166;
    private javax.swing.JLabel jq168;
    private javax.swing.JLabel jq169;
    private javax.swing.JLabel jq170;
    private javax.swing.JLabel jq171;
    private javax.swing.JLabel jq172;
    private javax.swing.JLabel jq173;
    private javax.swing.JLabel jq174;
    private javax.swing.JLabel jq175;
    private javax.swing.JLabel jq176;
    private javax.swing.JLabel jq177;
    private javax.swing.JLabel jq178;
    private javax.swing.JLabel jq179;
    private javax.swing.JLabel jq180;
    private javax.swing.JLabel jq181;
    private javax.swing.JLabel l9;
    private javax.swing.JLabel titulo8;
    // End of variables declaration//GEN-END:variables
}
