/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogomemoria.gui;

/**
 *
 * @author Aluno
 */
public class JogoMemoriaJPanelMedio extends javax.swing.JPanel {

    /**
     * Creates new form JogoMemoriaJPanelMedio
     */
    public JogoMemoriaJPanelMedio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        LB4 = new javax.swing.JLabel();
        LB3 = new javax.swing.JLabel();
        LB2 = new javax.swing.JLabel();
        LB1 = new javax.swing.JLabel();
        LB6 = new javax.swing.JLabel();
        LB7 = new javax.swing.JLabel();
        LB8 = new javax.swing.JLabel();
        LB9 = new javax.swing.JLabel();
        LB14 = new javax.swing.JLabel();
        LB13 = new javax.swing.JLabel();
        LB12 = new javax.swing.JLabel();
        LB11 = new javax.swing.JLabel();
        LB16 = new javax.swing.JLabel();
        LB17 = new javax.swing.JLabel();
        LB18 = new javax.swing.JLabel();
        LB19 = new javax.swing.JLabel();
        LB5 = new javax.swing.JLabel();
        LB10 = new javax.swing.JLabel();
        LB15 = new javax.swing.JLabel();
        LB20 = new javax.swing.JLabel();
        LB21 = new javax.swing.JLabel();
        LB22 = new javax.swing.JLabel();
        LB23 = new javax.swing.JLabel();
        LB24 = new javax.swing.JLabel();
        LB30 = new javax.swing.JLabel();
        LB29 = new javax.swing.JLabel();
        LB28 = new javax.swing.JLabel();
        LB26 = new javax.swing.JLabel();
        LB25 = new javax.swing.JLabel();
        LB27 = new javax.swing.JLabel();
        LB31 = new javax.swing.JLabel();
        LB32 = new javax.swing.JLabel();
        LB33 = new javax.swing.JLabel();
        LB34 = new javax.swing.JLabel();
        LB35 = new javax.swing.JLabel();
        LB36 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));
        setForeground(new java.awt.Color(153, 255, 255));

        lblTitulo.setBackground(new java.awt.Color(102, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        lblTitulo.setText("Jogo da Memória");

        lblTime.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 0, 0));
        lblTime.setText("Last Time");

        LB4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/15.jpg"))); // NOI18N

        LB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/9.jpg"))); // NOI18N

        LB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/9.jpg"))); // NOI18N

        LB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1.jpg"))); // NOI18N

        LB6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/12.jpg"))); // NOI18N

        LB7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7.jpg"))); // NOI18N

        LB8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/27.jpg"))); // NOI18N

        LB9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/12.jpg"))); // NOI18N

        LB14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/25_1.png"))); // NOI18N

        LB13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/27.jpg"))); // NOI18N

        LB12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/6.jpg"))); // NOI18N

        LB11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/15.jpg"))); // NOI18N

        LB16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1.jpg"))); // NOI18N

        LB17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/6.jpg"))); // NOI18N

        LB18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7.jpg"))); // NOI18N

        LB19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/25_1.png"))); // NOI18N

        LB5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/11.jpg"))); // NOI18N

        LB10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/11.jpg"))); // NOI18N

        LB15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/17.jpg"))); // NOI18N

        LB20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/17.jpg"))); // NOI18N

        LB21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/23.jpg"))); // NOI18N

        LB22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/23.jpg"))); // NOI18N

        LB23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/21.jpg"))); // NOI18N

        LB24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/21.jpg"))); // NOI18N

        LB30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/26.png"))); // NOI18N

        LB29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/26.png"))); // NOI18N

        LB28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/5.jpg"))); // NOI18N

        LB26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/19.jpg"))); // NOI18N

        LB25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/19.jpg"))); // NOI18N

        LB27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/5.jpg"))); // NOI18N

        LB31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2.jpg"))); // NOI18N

        LB32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2.jpg"))); // NOI18N

        LB33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/20.jpg"))); // NOI18N

        LB34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/20.jpg"))); // NOI18N

        LB35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24.jpg"))); // NOI18N

        LB36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(lblTime))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LB1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LB2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LB3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LB6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LB7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LB8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LB11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LB12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LB13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LB14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LB15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LB28))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LB9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LB10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LB29))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LB4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LB5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LB30))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB16)
                            .addComponent(LB21)
                            .addComponent(LB31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB17)
                            .addComponent(LB22)
                            .addComponent(LB32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB18)
                            .addComponent(LB23)
                            .addComponent(LB33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LB19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LB20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LB26))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LB24)
                                    .addComponent(LB34))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LB25)
                                    .addComponent(LB35))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LB36)
                                    .addComponent(LB27))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB1)
                            .addComponent(LB2)
                            .addComponent(LB4)
                            .addComponent(LB3)
                            .addComponent(LB5)
                            .addComponent(LB30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LB6)
                                    .addComponent(LB7)
                                    .addComponent(LB9)
                                    .addComponent(LB10)
                                    .addComponent(LB29))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LB11)
                                    .addComponent(LB14)
                                    .addComponent(LB15)
                                    .addComponent(LB28)))
                            .addComponent(LB8)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LB13)
                        .addComponent(LB12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LB16)
                        .addComponent(LB17)
                        .addComponent(LB18))
                    .addComponent(LB19)
                    .addComponent(LB20)
                    .addComponent(LB26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB21)
                    .addComponent(LB22)
                    .addComponent(LB23)
                    .addComponent(LB24)
                    .addComponent(LB25)
                    .addComponent(LB27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB31)
                    .addComponent(LB32)
                    .addComponent(LB33)
                    .addComponent(LB34)
                    .addComponent(LB35)
                    .addComponent(LB36))
                .addGap(0, 10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB1;
    private javax.swing.JLabel LB10;
    private javax.swing.JLabel LB11;
    private javax.swing.JLabel LB12;
    private javax.swing.JLabel LB13;
    private javax.swing.JLabel LB14;
    private javax.swing.JLabel LB15;
    private javax.swing.JLabel LB16;
    private javax.swing.JLabel LB17;
    private javax.swing.JLabel LB18;
    private javax.swing.JLabel LB19;
    private javax.swing.JLabel LB2;
    private javax.swing.JLabel LB20;
    private javax.swing.JLabel LB21;
    private javax.swing.JLabel LB22;
    private javax.swing.JLabel LB23;
    private javax.swing.JLabel LB24;
    private javax.swing.JLabel LB25;
    private javax.swing.JLabel LB26;
    private javax.swing.JLabel LB27;
    private javax.swing.JLabel LB28;
    private javax.swing.JLabel LB29;
    private javax.swing.JLabel LB3;
    private javax.swing.JLabel LB30;
    private javax.swing.JLabel LB31;
    private javax.swing.JLabel LB32;
    private javax.swing.JLabel LB33;
    private javax.swing.JLabel LB34;
    private javax.swing.JLabel LB35;
    private javax.swing.JLabel LB36;
    private javax.swing.JLabel LB4;
    private javax.swing.JLabel LB5;
    private javax.swing.JLabel LB6;
    private javax.swing.JLabel LB7;
    private javax.swing.JLabel LB8;
    private javax.swing.JLabel LB9;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
