/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogomemoria.gui;

import javax.swing.JPanel;

/**
 *
 * @author isamo
 */
public class JogoMemoriaTabuleiro extends javax.swing.JPanel {

    /**
     * Creates new form JogoMemoriaTabuleiro
     */
    public JogoMemoriaTabuleiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sppTabuleiro = new javax.swing.JSplitPane();
        jogoMemoriaJInfo1 = new jogomemoria.gui.JogoMemoriaJInfo();

        setLayout(new java.awt.BorderLayout());

        sppTabuleiro.setRightComponent(jogoMemoriaJInfo1);

        add(sppTabuleiro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jogomemoria.gui.JogoMemoriaJInfo jogoMemoriaJInfo1;
    private javax.swing.JSplitPane sppTabuleiro;
    // End of variables declaration//GEN-END:variables

    
    public void mostrarTabuleiro(JPanel pnl) {
        sppTabuleiro.setLeftComponent(pnl);
    }
    
    /**
     * @return the sppTabuleiro
     */
    public javax.swing.JSplitPane getSppTabuleiro() {
        return sppTabuleiro;
    }

    /**
     * @param sppTabuleiro the sppTabuleiro to set
     */
    public void setSppTabuleiro(javax.swing.JSplitPane sppTabuleiro) {
        this.sppTabuleiro = sppTabuleiro;
    }
}
