/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogomemoria.gui;

/**
 *
 * @author Aluno
 */
public class JogoMemoriaJPanelMedio extends javax.swing.JPanel {

    /**
     * Creates new form JogoMemoriaJPanelMedio
     */
    public JogoMemoriaJPanelMedio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblImg4 = new javax.swing.JLabel();
        lblImg3 = new javax.swing.JLabel();
        lblImg2 = new javax.swing.JLabel();
        lblImg1 = new javax.swing.JLabel();
        lblImg7 = new javax.swing.JLabel();
        lblImg8 = new javax.swing.JLabel();
        lblImg9 = new javax.swing.JLabel();
        lblImg10 = new javax.swing.JLabel();
        lblImg16 = new javax.swing.JLabel();
        lblImg15 = new javax.swing.JLabel();
        lblImg14 = new javax.swing.JLabel();
        lblImg13 = new javax.swing.JLabel();
        lblImg19 = new javax.swing.JLabel();
        lblImg20 = new javax.swing.JLabel();
        lblImg21 = new javax.swing.JLabel();
        lblImg22 = new javax.swing.JLabel();
        lblImg5 = new javax.swing.JLabel();
        lblImg11 = new javax.swing.JLabel();
        lblImg17 = new javax.swing.JLabel();
        lblImg23 = new javax.swing.JLabel();
        lblImg25 = new javax.swing.JLabel();
        lblImg26 = new javax.swing.JLabel();
        lblImg27 = new javax.swing.JLabel();
        lblImg28 = new javax.swing.JLabel();
        lblImg6 = new javax.swing.JLabel();
        lblImg12 = new javax.swing.JLabel();
        lblImg18 = new javax.swing.JLabel();
        lblImg24 = new javax.swing.JLabel();
        lblImg29 = new javax.swing.JLabel();
        lblImg30 = new javax.swing.JLabel();
        lblImg31 = new javax.swing.JLabel();
        lblImg32 = new javax.swing.JLabel();
        lblImg33 = new javax.swing.JLabel();
        lblImg34 = new javax.swing.JLabel();
        lblImg35 = new javax.swing.JLabel();
        lblImg36 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));
        setForeground(new java.awt.Color(153, 255, 255));

        lblTitulo.setBackground(new java.awt.Color(102, 255, 255));
        lblTitulo.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        lblTitulo.setText("Jogo da Memória");

        lblTime.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 0, 0));
        lblTime.setText("Last Time");

        lblImg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/15.jpg"))); // NOI18N

        lblImg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/9.jpg"))); // NOI18N

        lblImg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/9.jpg"))); // NOI18N

        lblImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1.jpg"))); // NOI18N

        lblImg7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/12.jpg"))); // NOI18N

        lblImg8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7.jpg"))); // NOI18N

        lblImg9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/27.jpg"))); // NOI18N

        lblImg10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/12.jpg"))); // NOI18N

        lblImg16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/25_1.png"))); // NOI18N

        lblImg15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/27.jpg"))); // NOI18N

        lblImg14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/6.jpg"))); // NOI18N

        lblImg13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/15.jpg"))); // NOI18N

        lblImg19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1.jpg"))); // NOI18N

        lblImg20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/6.jpg"))); // NOI18N

        lblImg21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7.jpg"))); // NOI18N

        lblImg22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/25_1.png"))); // NOI18N

        lblImg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/11.jpg"))); // NOI18N

        lblImg11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/11.jpg"))); // NOI18N

        lblImg17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/17.jpg"))); // NOI18N

        lblImg23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/17.jpg"))); // NOI18N

        lblImg25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/23.jpg"))); // NOI18N

        lblImg26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/23.jpg"))); // NOI18N

        lblImg27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/21.jpg"))); // NOI18N

        lblImg28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/21.jpg"))); // NOI18N

        lblImg6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/26.png"))); // NOI18N

        lblImg12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/26.png"))); // NOI18N

        lblImg18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/5.jpg"))); // NOI18N

        lblImg24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/19.jpg"))); // NOI18N

        lblImg29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/19.jpg"))); // NOI18N

        lblImg30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/5.jpg"))); // NOI18N

        lblImg31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2.jpg"))); // NOI18N

        lblImg32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2.jpg"))); // NOI18N

        lblImg33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/20.jpg"))); // NOI18N

        lblImg34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/20.jpg"))); // NOI18N

        lblImg35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24.jpg"))); // NOI18N

        lblImg36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(lblTime))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImg1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImg2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImg3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImg7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImg8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImg9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImg13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImg14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImg15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImg16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblImg17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImg18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImg10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImg11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImg12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImg4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImg5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImg6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImg19)
                            .addComponent(lblImg25)
                            .addComponent(lblImg31))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImg20)
                            .addComponent(lblImg26)
                            .addComponent(lblImg32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImg21)
                            .addComponent(lblImg27)
                            .addComponent(lblImg33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblImg22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblImg23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblImg24))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblImg28)
                                    .addComponent(lblImg34))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblImg29)
                                    .addComponent(lblImg35))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblImg36)
                                    .addComponent(lblImg30))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblImg1)
                            .addComponent(lblImg2)
                            .addComponent(lblImg4)
                            .addComponent(lblImg3)
                            .addComponent(lblImg5)
                            .addComponent(lblImg6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblImg7)
                                    .addComponent(lblImg8)
                                    .addComponent(lblImg10)
                                    .addComponent(lblImg11)
                                    .addComponent(lblImg12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblImg13)
                                    .addComponent(lblImg16)
                                    .addComponent(lblImg17)
                                    .addComponent(lblImg18)))
                            .addComponent(lblImg9)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblImg15)
                        .addComponent(lblImg14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblImg19)
                        .addComponent(lblImg20)
                        .addComponent(lblImg21))
                    .addComponent(lblImg22)
                    .addComponent(lblImg23)
                    .addComponent(lblImg24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImg25)
                    .addComponent(lblImg26)
                    .addComponent(lblImg27)
                    .addComponent(lblImg28)
                    .addComponent(lblImg29)
                    .addComponent(lblImg30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImg31)
                    .addComponent(lblImg32)
                    .addComponent(lblImg33)
                    .addComponent(lblImg34)
                    .addComponent(lblImg35)
                    .addComponent(lblImg36))
                .addGap(0, 10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImg1;
    private javax.swing.JLabel lblImg10;
    private javax.swing.JLabel lblImg11;
    private javax.swing.JLabel lblImg12;
    private javax.swing.JLabel lblImg13;
    private javax.swing.JLabel lblImg14;
    private javax.swing.JLabel lblImg15;
    private javax.swing.JLabel lblImg16;
    private javax.swing.JLabel lblImg17;
    private javax.swing.JLabel lblImg18;
    private javax.swing.JLabel lblImg19;
    private javax.swing.JLabel lblImg2;
    private javax.swing.JLabel lblImg20;
    private javax.swing.JLabel lblImg21;
    private javax.swing.JLabel lblImg22;
    private javax.swing.JLabel lblImg23;
    private javax.swing.JLabel lblImg24;
    private javax.swing.JLabel lblImg25;
    private javax.swing.JLabel lblImg26;
    private javax.swing.JLabel lblImg27;
    private javax.swing.JLabel lblImg28;
    private javax.swing.JLabel lblImg29;
    private javax.swing.JLabel lblImg3;
    private javax.swing.JLabel lblImg30;
    private javax.swing.JLabel lblImg31;
    private javax.swing.JLabel lblImg32;
    private javax.swing.JLabel lblImg33;
    private javax.swing.JLabel lblImg34;
    private javax.swing.JLabel lblImg35;
    private javax.swing.JLabel lblImg36;
    private javax.swing.JLabel lblImg4;
    private javax.swing.JLabel lblImg5;
    private javax.swing.JLabel lblImg6;
    private javax.swing.JLabel lblImg7;
    private javax.swing.JLabel lblImg8;
    private javax.swing.JLabel lblImg9;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
