/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogomemoria.gui;

/**
 *
 * @author isamo
 */
public class JogoMemoriaFormFacil extends javax.swing.JFrame {

    /**
     * Creates new form JogoMemoriaFormFacil
     */
    public JogoMemoriaFormFacil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        titulo = new javax.swing.JLabel();
        jq1 = new javax.swing.JLabel();
        jq2 = new javax.swing.JLabel();
        jq3 = new javax.swing.JLabel();
        jq4 = new javax.swing.JLabel();
        jq5 = new javax.swing.JLabel();
        jq6 = new javax.swing.JLabel();
        jq7 = new javax.swing.JLabel();
        jq8 = new javax.swing.JLabel();
        jq9 = new javax.swing.JLabel();
        jq10 = new javax.swing.JLabel();
        jq11 = new javax.swing.JLabel();
        jq12 = new javax.swing.JLabel();
        jq13 = new javax.swing.JLabel();
        jq14 = new javax.swing.JLabel();
        jq15 = new javax.swing.JLabel();
        jq16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        titulo.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        titulo.setText("Jogo da Memória");

        jq1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1.jpg"))); // NOI18N

        jq2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/10.jpg"))); // NOI18N

        jq3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/13.jpg"))); // NOI18N

        jq4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/15.jpg"))); // NOI18N

        jq5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/13.jpg"))); // NOI18N

        jq6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/12.jpg"))); // NOI18N

        jq7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/1.jpg"))); // NOI18N

        jq8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/10.jpg"))); // NOI18N

        jq9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/15.jpg"))); // NOI18N

        jq10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/12.jpg"))); // NOI18N

        jq11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/6.jpg"))); // NOI18N

        jq12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/6.jpg"))); // NOI18N

        jq13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/9.jpg"))); // NOI18N

        jq14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7.jpg"))); // NOI18N

        jq15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/9.jpg"))); // NOI18N

        jq16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/7.jpg"))); // NOI18N

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titulo))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jq5)
                            .addComponent(jq1)
                            .addComponent(jq9)
                            .addComponent(jq13))
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jq2)
                                .addGap(18, 18, 18)
                                .addComponent(jq3)
                                .addGap(18, 18, 18)
                                .addComponent(jq4))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(jq10)
                                        .addGap(18, 18, 18)
                                        .addComponent(jq11)
                                        .addGap(18, 18, 18)
                                        .addComponent(jq12))
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(jq6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jq7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jq8))
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(jq14)
                                        .addGap(18, 18, 18)
                                        .addComponent(jq15)
                                        .addGap(18, 18, 18)
                                        .addComponent(jq16)))))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jq4)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(titulo)
                        .addGap(41, 41, 41)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jq1)
                            .addComponent(jq2)
                            .addComponent(jq3))))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jq5)
                    .addComponent(jq6)
                    .addComponent(jq7)
                    .addComponent(jq8))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jq9)
                    .addComponent(jq10)
                    .addComponent(jq11)
                    .addComponent(jq12))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jq13)
                    .addComponent(jq14)
                    .addComponent(jq15)
                    .addComponent(jq16))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoMemoriaFormFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoMemoriaFormFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoMemoriaFormFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoMemoriaFormFacil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoMemoriaFormFacil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jq1;
    private javax.swing.JLabel jq10;
    private javax.swing.JLabel jq11;
    private javax.swing.JLabel jq12;
    private javax.swing.JLabel jq13;
    private javax.swing.JLabel jq14;
    private javax.swing.JLabel jq15;
    private javax.swing.JLabel jq16;
    private javax.swing.JLabel jq2;
    private javax.swing.JLabel jq3;
    private javax.swing.JLabel jq4;
    private javax.swing.JLabel jq5;
    private javax.swing.JLabel jq6;
    private javax.swing.JLabel jq7;
    private javax.swing.JLabel jq8;
    private javax.swing.JLabel jq9;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
